### ISSUE TITLE
stop creating package.json files by hand

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails-generate-controller#2]
It's obvious that the package json files for many balderdash projects are hand-cobbled, resulting in missing `repository` fields on npmjs.org, use of the outdated `~` dependency version style, and other sporadic oddities. The missing repo field, for example, makes it inconvenient to track down the source for published modules.

Please just run `npm init` to keep things standardized and so that the packages follow npm convention. Thanks.

**Comment by loicsaintroch** [comment]
Thank you for your feedback @tjwebb. I think it should be better to let @mikermcneil and @sgress454 on the main Sails repo.
